package com.github.k1rakishou.chan.core.di.module.activity

import androidx.savedstate.SavedStateRegistryOwner

class ActivityScopedSavedStateRegistryOwner(val savedStateRegistryOwner: SavedStateRegistryOwner)