package com.github.k1rakishou.core_themes

import android.graphics.Color

class DefaultLightTheme(
  name: String = "Default light theme",
  isLightTheme: Boolean = true,
  lightStatusBar: Boolean = true,
  lightNavBar: Boolean = true,
  accentColor: Int = Color.parseColor("#af0a0f"),
  primaryColor: Int = Color.parseColor("#3c8f52"),
  backColor: Int = Color.parseColor("#EEF2FF"),
  backColorSecondary: Int = Color.parseColor("#d6daf0"),
  errorColor: Int = Color.parseColor("#ff4444"),
  textColorPrimary: Int = Color.parseColor("#000000"),
  textColorSecondary: Int = Color.parseColor("#6b6b6b"),
  textColorHint: Int = Color.parseColor("#8c8c8c"),
  postHighlightedColor: Int = Color.parseColor("#60a3a6b5"),
  postSavedReplyColor: Int = Color.parseColor("#3b59f5"),
  postSubjectColor: Int = Color.parseColor("#0F0C5D"),
  postDetailsColor: Int = Color.parseColor("#656565"),
  postNameColor: Int = Color.parseColor("#117743"),
  postInlineQuoteColor: Int = Color.parseColor("#789922"),
  postQuoteColor: Int = Color.parseColor("#dd0000"),
  postHighlightQuoteColor: Int = Color.parseColor("#780202"),
  postLinkColor: Int = Color.parseColor("#dd0000"),
  postSpoilerColor: Int = Color.parseColor("#000000"),
  postSpoilerRevealTextColor: Int = Color.parseColor("#ffffff"),
  postUnseenLabelColor: Int = errorColor,
  dividerColor: Int = Color.parseColor("#20000000"),
  bookmarkCounterNotWatchingColor: Int = Color.parseColor("#898989"),
  bookmarkCounterHasRepliesColor: Int = Color.parseColor("#ff5744"),
  bookmarkCounterNormalColor: Int = Color.parseColor("#6033e5"),
  scrollbarTrackColor: Int = Color.parseColor("#ffbababa"),
  scrollbarThumbColorNormal: Int = Color.parseColor("#ff262626"),
  scrollbarThumbColorDragged: Int = accentColor,
) : ChanTheme(
  name = name,
  isLightTheme = isLightTheme,
  lightStatusBar = lightStatusBar,
  lightNavBar = lightNavBar,
  accentColor = accentColor,
  primaryColor = primaryColor,
  backColor = backColor,
  backColorSecondary = backColorSecondary,
  errorColor = errorColor,
  textColorPrimary = textColorPrimary,
  textColorSecondary = textColorSecondary,
  textColorHint = textColorHint,
  postHighlightedColor = postHighlightedColor,
  postSavedReplyColor = postSavedReplyColor,
  postSubjectColor = postSubjectColor,
  postDetailsColor = postDetailsColor,
  postNameColor = postNameColor,
  postInlineQuoteColor = postInlineQuoteColor,
  postQuoteColor = postQuoteColor,
  postHighlightQuoteColor = postHighlightQuoteColor,
  postLinkColor = postLinkColor,
  postSpoilerColor = postSpoilerColor,
  postSpoilerRevealTextColor = postSpoilerRevealTextColor,
  postUnseenLabelColor = postUnseenLabelColor,
  dividerColor = dividerColor,
  bookmarkCounterNotWatchingColor = bookmarkCounterNotWatchingColor,
  bookmarkCounterHasRepliesColor = bookmarkCounterHasRepliesColor,
  bookmarkCounterNormalColor = bookmarkCounterNormalColor,
  scrollbarTrackColor = scrollbarTrackColor,
  scrollbarThumbColorNormal = scrollbarThumbColorNormal,
  scrollbarThumbColorDragged = scrollbarThumbColorDragged
)