package com.github.k1rakishou.core_themes

import android.graphics.Color

class HalloweenTheme(
  name: String = "Halloween",
  isLightTheme: Boolean = false,
  lightStatusBar: Boolean = true,
  lightNavBar: Boolean = true,
  accentColor: Int = Color.parseColor("#C37D35"),
  primaryColor: Int = Color.parseColor("#000000"),
  backColor: Int = Color.parseColor("#171526"),
  backColorSecondary: Int = Color.parseColor("#03001A"),
  errorColor: Int = Color.parseColor("#ff0000"),
  textColorPrimary: Int = Color.parseColor("#dbd9d9"),
  textColorSecondary: Int = Color.parseColor("#b8b8b8"),
  textColorHint: Int = Color.parseColor("#878787"),
  postHighlightedColor: Int = Color.parseColor("#a0212730"),
  postSavedReplyColor: Int = Color.parseColor("#cf8357"),
  postSubjectColor: Int = Color.parseColor("#d95c43"),
  postDetailsColor: Int = Color.parseColor("#919191"),
  postNameColor: Int = Color.parseColor("#919191"),
  postInlineQuoteColor: Int = Color.parseColor("#b76d5e"),
  postQuoteColor: Int = Color.parseColor("#d77841"),
  postHighlightQuoteColor: Int = Color.parseColor("#d77841"),
  postLinkColor: Int = Color.parseColor("#d77841"),
  postSpoilerColor: Int = Color.parseColor("#01060a"),
  postSpoilerRevealTextColor: Int = Color.parseColor("#b8b8b8"),
  postUnseenLabelColor: Int = Color.parseColor("#d38d70"),
  dividerColor: Int = Color.parseColor("#303438"),
  bookmarkCounterNotWatchingColor: Int = Color.parseColor("#5e5e5e"),
  bookmarkCounterHasRepliesColor: Int = Color.parseColor("#d77841"),
  bookmarkCounterNormalColor: Int = Color.parseColor("#b39d91"),
  scrollbarTrackColor: Int = Color.parseColor("#ffbababa"),
  scrollbarThumbColorNormal: Int = Color.parseColor("#ff262626"),
  scrollbarThumbColorDragged: Int = accentColor,
) : ChanTheme(
  name = name,
  isLightTheme = isLightTheme,
  lightStatusBar = lightStatusBar,
  lightNavBar = lightNavBar,
  accentColor = accentColor,
  primaryColor = primaryColor,
  backColor = backColor,
  backColorSecondary = backColorSecondary,
  errorColor = errorColor,
  textColorPrimary = textColorPrimary,
  textColorSecondary = textColorSecondary,
  textColorHint = textColorHint,
  postHighlightedColor = postHighlightedColor,
  postSavedReplyColor = postSavedReplyColor,
  postSubjectColor = postSubjectColor,
  postDetailsColor = postDetailsColor,
  postNameColor = postNameColor,
  postInlineQuoteColor = postInlineQuoteColor,
  postQuoteColor = postQuoteColor,
  postHighlightQuoteColor = postHighlightQuoteColor,
  postLinkColor = postLinkColor,
  postSpoilerColor = postSpoilerColor,
  postSpoilerRevealTextColor = postSpoilerRevealTextColor,
  postUnseenLabelColor = postUnseenLabelColor,
  dividerColor = dividerColor,
  bookmarkCounterNotWatchingColor = bookmarkCounterNotWatchingColor,
  bookmarkCounterHasRepliesColor = bookmarkCounterHasRepliesColor,
  bookmarkCounterNormalColor = bookmarkCounterNormalColor,
  scrollbarTrackColor = scrollbarTrackColor,
  scrollbarThumbColorNormal = scrollbarThumbColorNormal,
  scrollbarThumbColorDragged = scrollbarThumbColorDragged
)