package com.github.k1rakishou.core_themes

data class Theme(
  override val name: String,
  override val isLightTheme: Boolean,
  override val lightStatusBar: Boolean,
  override val lightNavBar: Boolean,
  override val accentColor: Int,
  override val primaryColor: Int,
  override val backColor: Int,
  override val backColorSecondary: Int,
  override val errorColor: Int,
  override val textColorPrimary: Int,
  override val textColorSecondary: Int,
  override val textColorHint: Int,
  override val postHighlightedColor: Int,
  override val postSavedReplyColor: Int,
  override val postSubjectColor: Int,
  override val postDetailsColor: Int,
  override val postNameColor: Int,
  override val postInlineQuoteColor: Int,
  override val postQuoteColor: Int,
  override val postHighlightQuoteColor: Int,
  override val postLinkColor: Int,
  override val postSpoilerColor: Int,
  override val postSpoilerRevealTextColor: Int,
  override val postUnseenLabelColor: Int,
  override val dividerColor: Int,
  override val bookmarkCounterNotWatchingColor: Int,
  override val bookmarkCounterHasRepliesColor: Int,
  override val bookmarkCounterNormalColor: Int,
) : ChanTheme() {

  override fun copyTheme(
    name: String,
    isLightTheme: Boolean,
    lightStatusBar: Boolean,
    lightNavBar: Boolean,
    accentColor: Int,
    primaryColor: Int,
    backColor: Int,
    backColorSecondary: Int,
    errorColor: Int,
    textColorPrimary: Int,
    textColorSecondary: Int,
    textColorHint: Int,
    postHighlightedColor: Int,
    postSavedReplyColor: Int,
    postSubjectColor: Int,
    postDetailsColor: Int,
    postNameColor: Int,
    postInlineQuoteColor: Int,
    postQuoteColor: Int,
    postHighlightQuoteColor: Int,
    postLinkColor: Int,
    postSpoilerColor: Int,
    postSpoilerRevealTextColor: Int,
    postUnseenLabelColor: Int,
    dividerColor: Int,
    bookmarkCounterNotWatchingColor: Int,
    bookmarkCounterHasRepliesColor: Int,
    bookmarkCounterNormalColor: Int
  ): ChanTheme {
    return copy(
      name = name,
      isLightTheme = isLightTheme,
      lightStatusBar = lightStatusBar,
      lightNavBar = lightNavBar,
      accentColor = accentColor,
      primaryColor = primaryColor,
      backColor = backColor,
      backColorSecondary = backColorSecondary,
      errorColor = errorColor,
      textColorPrimary = textColorPrimary,
      textColorSecondary = textColorSecondary,
      textColorHint = textColorHint,
      postHighlightedColor = postHighlightedColor,
      postSavedReplyColor = postSavedReplyColor,
      postSubjectColor = postSubjectColor,
      postDetailsColor = postDetailsColor,
      postNameColor = postNameColor,
      postInlineQuoteColor = postInlineQuoteColor,
      postQuoteColor = postQuoteColor,
      postHighlightQuoteColor = postHighlightQuoteColor,
      postLinkColor = postLinkColor,
      postSpoilerColor = postSpoilerColor,
      postSpoilerRevealTextColor = postSpoilerRevealTextColor,
      postUnseenLabelColor = postUnseenLabelColor,
      dividerColor = dividerColor,
      bookmarkCounterNotWatchingColor = bookmarkCounterNotWatchingColor,
      bookmarkCounterHasRepliesColor = bookmarkCounterHasRepliesColor,
      bookmarkCounterNormalColor = bookmarkCounterNormalColor
    )
  }

}